apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app.kubernetes.io/name: vw-vault
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Release.Name }}-vault-internal
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: vw-vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vw-vault
    spec:
      serviceAccountName: {{ .Release.Name }}-vault
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - vault
            - server
            - -config=/vault/config/vault.hcl
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_CLUSTER_ADDR
              value: "https://$(POD_NAME).{{ .Release.Name }}-vault-internal:8201"
            - name: VAULT_API_ADDR
              value: "http://$(POD_NAME).{{ .Release.Name }}-vault-internal:8200"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_RAFT_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: {{ .Values.service.apiPort }}
            - name: cluster
              containerPort: {{ .Values.service.clusterPort }}
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /vault/data
            - name: config
              mountPath: /vault/config
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-vault-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.storageClass }}
        storageClassName: {{ .Values.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
