apiVersion: v1
kind: Service
metadata:
  name: {{ include "vw-sfu-janus.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vw-sfu-janus.name" . }}
  annotations:
    metallb.universe.tf/address-pool: "{{ .Values.service.metallbAddressPool }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "vw-sfu-janus.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
{{- $start := int .Values.service.rtpPortStart -}}
{{- $end := int .Values.service.rtpPortEnd -}}
{{- range $p := untilStep $start (add $end 1) 1 }}
    - name: rtp-{{ $p }}
      port: {{ $p }}
      targetPort: {{ $p }}
      protocol: UDP
{{- end }}
