apiVersion: v1
kind: Service
metadata:
  name: vw-grafana
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: vw-grafana }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
