apiVersion: apps/v1
kind: Deployment
metadata:
  name: vw-loki
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: vw-loki }
  template:
    metadata:
      labels: { app: vw-loki }
    spec:
      containers:
        - name: loki
          image: {{ .Values.images.loki }}
          args: ["-config.file=/etc/loki/loki.yml"]
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: cfg
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: cfg
          configMap:
            name: vw-loki-config
        - name: data
          emptyDir: {}
