apiVersion: apps/v1
kind: Deployment
metadata:
  name: vw-policy
  labels:
    app: vw-policy
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: vw-policy
  template:
    metadata:
      labels:
        app: vw-policy
      annotations:
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-tls.crt: "{{ .Values.vault.pkiPath }}"
        vault.hashicorp.com/role: "{{ .Values.vault.role | default "policy" }}"
        {{- end }}
    spec:
      securityContext:
{ toYaml .Values.podSecurityContext | indent 8 }
      containers:
        - name: vw-policy
          image: "{{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          ports:
            - containerPort: { { .Values.service.port } }
          env:
{- range $k, $v := .Values.env }
            - name: { $k }
              value: "{ $v }"
{- end }
          securityContext:
{ toYaml .Values.securityContext | indent 12 }
          resources:
{ toYaml .Values.resources | indent 12 }
