apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vw-compositor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vw-compositor.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vw-compositor.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vw-compositor.name" . }}
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: vw-compositor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8005
          env:
            - name: VW_POLICY_SERVICE_URL
              value: "{{ .Values.env.VW_POLICY_SERVICE_URL }}"
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
