apiVersion: v1
kind: Service
metadata:
  name: {{ include "vw-compositor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vw-compositor.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "vw-compositor.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
