all:
  vars:
    ansible_user: ubuntu
    ansible_become: true

  children:
    wall_controllers:
      hosts:
        wall-controller-01:
          ansible_host: 10.50.10.11
        wall-controller-02:
          ansible_host: 10.50.10.12
        wall-controller-03:
          ansible_host: 10.50.10.13
        wall-controller-04:
          ansible_host: 10.50.10.14

    tile_players:
      children:
        tile_players_1080p:
          hosts:
            tile-001: { ansible_host: 10.50.20.1 }
            tile-002: { ansible_host: 10.50.20.2 }
        big_screen_players_4k:
          hosts:
            bigscreen-01: { ansible_host: 10.50.30.1 }
            bigscreen-02: { ansible_host: 10.50.30.2 }
            bigscreen-03: { ansible_host: 10.50.30.3 }
            bigscreen-04: { ansible_host: 10.50.30.4 }

    source_agents:
      hosts:
        source-agent-01: { ansible_host: 10.50.40.1 }
        source-agent-02: { ansible_host: 10.50.40.2 }

    k8s_masters:
      hosts:
        k8s-master-01: { ansible_host: 10.50.1.11 }
        k8s-master-02: { ansible_host: 10.50.1.12 }
        k8s-master-03: { ansible_host: 10.50.1.13 }

    k8s_workers:
      hosts:
        k8s-worker-01: { ansible_host: 10.50.2.21 }
        k8s-worker-02: { ansible_host: 10.50.2.22 }
